function triggered_generateDailyReport() {
  const startTime = new Date();
  
  // Calculate Start of Today
  const now = new Date();
  const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const startOfTodayIso = Utilities.formatDate(startOfToday, Session.getScriptTimeZone(), "yyyy-MM-dd'T'HH:mm:ss");

  Logger.log("Starting Daily Report Generation for date: " + startOfTodayIso);

  // Search for all files modified today (excluding trashed files)
  // Note: We search globally as per requirement "any file created in Drive"
  const searchQuery = `modifiedDate > '${startOfTodayIso}' and trashed = false`;
  const files = DriveApp.searchFiles(searchQuery);

  const createdToday = [];
  const updatedToday = [];

  while (files.hasNext()) {
    const file = files.next();
    const createdDate = file.getDateCreated();
    const updatedDate = file.getLastUpdated();

    const fileInfo = {
      title: file.getName(),
      url: file.getUrl()
    };

    if (createdDate >= startOfToday) {
      createdToday.push(fileInfo);
    } else {
      updatedToday.push(fileInfo);
    }
  }

  // Sort lists alphabetically by title
  createdToday.sort((a, b) => a.title.localeCompare(b.title));
  updatedToday.sort((a, b) => a.title.localeCompare(b.title));

  // Find or Create Report Document
  const preferences = loadPreferences();
  let notesFolder;
  if (preferences && preferences.notesFolder) {
      const folders = DriveApp.getFoldersByName(preferences.notesFolder);
      if (folders.hasNext()) notesFolder = folders.next();
  }
  
  // Fallback to root or error if notes folder not found? 
  // triggered_makeTagIndex uses "Notes" folder by name hardcoded, let's use that to match existing patterns or preferences if available.
  // The prompt implies mimicking Tag List, which uses "Notes" folder.
  if (!notesFolder) {
     const folders = DriveApp.getFoldersByName("Notes"); // Fallback to hardcoded "Notes" like makeTagIndex
     if (folders.hasNext()) {
       notesFolder = folders.next();
     } else {
       Logger.log("Notes folder not found. Cannot create Daily Report.");
       return;
     }
  }

  const docName = 'Daily Report';
  const existingFiles = notesFolder.getFilesByName(docName);
  let doc;

  if (existingFiles.hasNext()) {
    const file = existingFiles.next();
    doc = DocumentApp.openById(file.getId());
    // Trash duplicates
    while(existingFiles.hasNext()){
      existingFiles.next().setTrashed(true);
    }
    Logger.log(`Opened existing Daily Report file.`);
  } else {
    doc = DocumentApp.create(docName);
    const file = DriveApp.getFileById(doc.getId());
    notesFolder.addFile(file);
    DriveApp.getRootFolder().removeFile(file);
    Logger.log(`Created new Daily Report file.`);
  }

  const body = doc.getBody();

  // Clear Body Safely (pattern from makeTagIndex)
  const titleParagraph = body.appendParagraph('Daily Report');
  titleParagraph.setHeading(DocumentApp.ParagraphHeading.TITLE);
  
  let bodySibling = titleParagraph.getPreviousSibling();
  while (bodySibling) {
    const prev = bodySibling.getPreviousSibling();
    body.removeChild(bodySibling);
    bodySibling = prev;
  }
  
  body.appendHorizontalRule();

  // Add Date/Source
  body.appendParagraph(`Report Date: ${Utilities.formatDate(now, Session.getScriptTimeZone(), "MM/dd/yyyy")}`);
  body.appendParagraph(`Source: Automated Trigger`);
  body.appendParagraph("");

  // Section: Created Today
  body.appendParagraph(`All Documents Created Today (${createdToday.length})`).setHeading(DocumentApp.ParagraphHeading.HEADING2);
  if (createdToday.length > 0) {
    createdToday.forEach(item => {
      body.appendListItem(item.title).setLinkUrl(item.url);
    });
  } else {
    body.appendParagraph("No documents created today.");
  }

  // Section: Updated Today
  body.appendParagraph(`All Documents Updated Today but Created Earlier (${updatedToday.length})`).setHeading(DocumentApp.ParagraphHeading.HEADING2);
  if (updatedToday.length > 0) {
    updatedToday.forEach(item => {
      body.appendListItem(item.title).setLinkUrl(item.url);
    });
  } else {
    body.appendParagraph("No documents updated today (that were created earlier).");
  }

  // Footer / Stats
  body.appendHorizontalRule();
  const endTime = new Date();
  const duration = (endTime.getTime() - startTime.getTime()) / 1000;
  
  body.appendParagraph(`Report run at: ${Utilities.formatDate(endTime, Session.getScriptTimeZone(), "MM/dd/yyyy, h:mm:ss a")}`);
  body.appendParagraph(`Duration of run: ${duration} seconds`);
  
  // Footer Standard
  let footer = doc.getFooter();
  if (!footer) footer = doc.addFooter();
  
  // Clear footer safely
  const footerTextPara = footer.appendParagraph('Generated by Quick Note Suite');
  footerTextPara.setLinkUrl("https://sites.google.com/view/quick-notes-suite/home");
  footerTextPara.setAlignment(DocumentApp.HorizontalAlignment.CENTER);
  
  let footerSibling = footerTextPara.getPreviousSibling();
  while (footerSibling) {
    const prev = footerSibling.getPreviousSibling();
    footer.removeChild(footerSibling);
    footerSibling = prev;
  }
  footer.insertHorizontalRule(0);

  doc.saveAndClose();
  Logger.log("Daily Report generation completed.");
}
